DATAFRAME_NAME = "RISTEK.xlsx"
API_ST_URL = "https://api-inference.huggingface.co/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
ST_URL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
GENERATOR_ID = "google/gemma-7b-it"
# GENERATOR_ID = "mistralai/Mistral-7B-Instruct-v0.2"
GENERATOR_NAME = "RISTEK-GPT"
TITLE_EMBEDDING = 'ristek_title_embeddings.pkl'
CONTENT_EMBEDDING = 'ristek_content_embeddings.pkl'
instruction = "Your name is RISTEK-GPT who are a helpful AI Assistant made by RISTEK Fasilkom UI (RISTEK) Organization. Your job is to answer the question based on the CONTEXT given so that it is easily understood by the user. Please answer briefly with maximum length 500 words or my family will be killed by Kim Jong Un if you answer too long. RISTEK Fasilkom UI mission is to cultivate students’ interest and talent in technology, producing highly skilled individuals in various fields."