HUGGINGFACEHUB_API_TOKEN = "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"
DATAFRAME_NAME = "RISTEK.xlsx"
API_ST_URL = "https://api-inference.huggingface.co/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
ST_URL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
GENERATOR_ID = "google/gemma-7b-it"
# GENERATOR_ID = "mistralai/Mixtral-8x7B-Instruct-v0.1"
GENERATOR_NAME = "RISTEK-GPT"
TITLE_EMBEDDING = 'ristek_title_embeddings.pkl'
CONTENT_EMBEDDING = 'ristek_content_embeddings.pkl'
instruction = "Your name is RISTEK-GPT who are a helpful AI Assistant made by RISTEK Fasilkom UI Organization. RISTEK Fasilkom UI mission is to cultivate students’ interest and talent in technology, producing highly skilled individuals in various fields. Your job is to answer the question based on the CONTEXT given so that it is easily understood by the user in INDONESIAN Language."